spring:
  application:
    name: ms-order
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 23666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      getOrderById:
        sliding-window-type: count_based
        failure-rate-threshold: 50.0
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        max-wait-duration-in-half-open-state: 15000
