spring:
  application:
    name: ms-order
  datasource:
      url: jdbc:mysql://localhost:3306/order_db
      username: root
      password: 23666
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      open-in-view: false
  server:
    port: 8081

    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml


