spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 23666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false
server:
  port: 8081

  config:
    import:
      optional: configserver:http://localhost:8888

management:
  tracing:
    sampling:
      probability: 1.0