spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: ms-product
            uri: http://localhost:9999
            predicates:
              - Path=/products/**
            filters:
              - RewritePath=/products/(?<segment>.*), /${segment}
          - id: ms-order
            uri: http://localhost:8081
            predicates:
              - Path=/orders/**
            filters:
              - RewritePath=/orders/(?<segment>.*), /${segment}
          - id: ms-payment
            uri: http://localhost:8082
            predicates:
              - Path=/payments/**
            filters:
              - RewritePath=/payments/(?<segment>.*), /${segment}

springDoc:
  swagger-ui:
    urls:
      - name: ms-product
        url: http://localhost:9999/v3/api-docs
      - name: ms-order
        url: http://localhost:8081/v3/api-docs
      - name: ms-payment
        url: http://localhost:8082/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 9090
